### ISSUE TITLE
Specify matplotlib required version ranges in manifest

### ISSUE THREAD

**Issue by leguyader** [mpld3/mpld3#547]
I've been trying to test mpld3, but nothing seems to work. I've been using for this the mpld3_demo.ipynb example. The matplotlib scatter plot renders correctly, but trying to get the interactive plot with:
```
import mpld3
mpld3.display(fig)
```
Produces the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 2
      1 import mpld3
----> 2 mpld3.display(fig)

File ~/.local/lib/python3.11/site-packages/mpld3/_display.py:316, in display(fig, closefig, local, **kwargs)
    314 if closefig:
    315     plt.close(fig)
--> 316 return HTML(fig_to_html(fig, **kwargs))

File ~/.local/lib/python3.11/site-packages/mpld3/_display.py:250, in fig_to_html(fig, d3_url, mpld3_url, no_extras, template_type, figid, use_http, include_libraries, **kwargs)
    247     raise ValueError("figid must not contain spaces")
    249 renderer = MPLD3Renderer()
--> 250 Exporter(renderer, close_mpl=False, **kwargs).run(fig)
    252 fig, figure_json, extra_css, extra_js = renderer.finished_figures[0]
    254 if no_extras:

File ~/.local/lib/python3.11/site-packages/mpld3/mplexporter/exporter.py:51, in Exporter.run(self, fig)
     49     import matplotlib.pyplot as plt
     50     plt.close(fig)
---> 51 self.crawl_fig(fig)

File ~/.local/lib/python3.11/site-packages/mpld3/mplexporter/exporter.py:118, in Exporter.crawl_fig(self, fig)
    115 with self.renderer.draw_figure(fig=fig,
    116                                props=utils.get_figure_properties(fig)):
    117     for ax in fig.axes:
--> 118         self.crawl_ax(ax)

File ~/.local/lib/python3.11/site-packages/mpld3/mplexporter/exporter.py:123, in Exporter.crawl_ax(self, ax)
    120 def crawl_ax(self, ax):
    121     """Crawl the axes and process all elements within"""
    122     with self.renderer.draw_axes(ax=ax,
--> 123                                  props=utils.get_axes_properties(ax)):
    124         for line in ax.lines:
    125             self.draw_line(ax, line)

File ~/.local/lib/python3.11/site-packages/mpld3/mplexporter/utils.py:303, in get_axes_properties(ax)
    298 domain = getattr(ax, 'get_{0}lim'.format(axname))()
    299 lim = domain
    300 if (
    301     (
    302         hasattr(matplotlib.dates, '_SwitchableDateConverter') and
--> 303         isinstance(axis.get_converter(), matplotlib.dates._SwitchableDateConverter)
    304     ) or (
    305         hasattr(matplotlib.dates, 'DateConverter') and
    306         isinstance(axis.get_converter(), matplotlib.dates.DateConverter)
    307     ) or (
    308         hasattr(matplotlib.dates, 'ConciseDateConverter') and
    309         isinstance(axis.get_converter(), matplotlib.dates.ConciseDateConverter)
    310     )
    311 ):
    312     scale = 'date'
    313     try:

AttributeError: 'XAxis' object has no attribute 'get_converter'
```
The matplotlib version is 3.8.2 (or 3.6.3 on another machine) and mpld3 version is 0.5.12.

**Comment by leguyader** [comment]
After upgrading matplotlib to 3.10.8, the demo notebook works.

**Comment by vladh** [comment]
Hey @leguyader, thanks for this. When we migrate to `pyproject.toml` very soon, the required matplotlib version ranges will be clearly specified. I'm leaving this issue open until then.
