### ISSUE TITLE
AttributeError: module 'matplotlib.dates' has no attribute '_SwitchableDateConverter'

### ISSUE THREAD

**Issue by AlexAdvent** [mpld3/mpld3#504]
I am using mpld3.fig_to_html form the last three months its working fine but from the last two days, it's showing error. All of my code stop workings. Can anyone suggest me how to solve this error?

error: AttributeError: module 'matplotlib.dates' has no attribute '_SwitchableDateConverter'

also this simple code throwing same error.
fig = plt.figure()
plt.scatter([1, 10], [5, 9])
html_graph = mpld3.fig_to_html(fig)

collab file: https://colab.research.google.com/drive/17W1_vfOZTYmhodzziNEC7wPiuZuF9Cc1?usp=sharing.

**Comment by vladh** [comment]
Sorry, this is my mistake! I'll fix it a moment, but if you'd like to get it working before then, you can update to matplotlib 3.5.0.

**Comment by vladh** [comment]
This should be fixed in 0.5.7 — could you please let me know if everything works for you now on matplotlib 3.2.1? Thanks!

**Comment by AlexAdvent** [comment]
it work with matplotlib==3.2.1 mpld3==0.5.7

**Comment by AlexAdvent** [comment]
@vladh  thanks for help
