### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by erprateek** [mpld3/mpld3#176]
Hi, 

It seemed to have installed properly but when I try to run the examples or the test plots, it gives the following error:

```
AttributeError: 'CompositeGenericTransform' object has no attribute 'contains_branch'
```

I am attaching the complete error for your reference:

```
prateek@prateek-VirtualBox:~/git/mpld3$ python process_testplots.py 
d3 url: https://mpld3.github.io/js/d3.v3.min.js
mpld3 url: https://mpld3.github.io/js/mpld3.v0.2git.js
plotting test_line_tooltips.py
Traceback (most recent call last):
  File "process_testplots.py", line 261, in <module>
    outfile, nolaunch = run_main()
  File "process_testplots.py", line 256, in run_main
    mpld3_url=args.mpld3_url)
  File "process_testplots.py", line 189, in combine_testplots
    fig_json.extend(result.iter_json())
  File "process_testplots.py", line 155, in iter_json
    Exporter(renderer, close_mpl=False).run(fig)
  File "/home/prateek/git/mpld3/mpld3/mplexporter/exporter.py", line 49, in run
    self.crawl_fig(fig)
  File "/home/prateek/git/mpld3/mpld3/mplexporter/exporter.py", line 116, in crawl_fig
    self.crawl_ax(ax)
  File "/home/prateek/git/mpld3/mpld3/mplexporter/exporter.py", line 123, in crawl_ax
    self.draw_line(ax, line)
  File "/home/prateek/git/mpld3/mpld3/mplexporter/exporter.py", line 179, in draw_line
    force_trans=force_trans)
  File "/home/prateek/git/mpld3/mpld3/mplexporter/exporter.py", line 96, in process_transform
    if transform.contains_branch(trans):
AttributeError: 'CompositeGenericTransform' object has no attribute 'contains_branch'
```

the create_example on the other hand gives a different error:

```
prateek@prateek-VirtualBox:~/git/mpld3$ python create_example.py 
/home/prateek/git/mpld3/mpld3/utils.py:24: DeprecationWarning: mpld3.show_d3 is deprecated and will be removed.  Use mpld3.show instead
  category=DeprecationWarning)
Traceback (most recent call last):
  File "create_example.py", line 73, in <module>
    show_d3()
  File "/home/prateek/git/mpld3/mpld3/utils.py", line 25, in new_func
    return func(*args, **kwargs)
  File "/home/prateek/git/mpld3/mpld3/_display.py", line 332, in show
    html = fig_to_html(fig, **kwargs)
  File "/home/prateek/git/mpld3/mpld3/_display.py", line 226, in fig_to_html
    Exporter(renderer, close_mpl=False, **kwargs).run(fig)
  File "/home/prateek/git/mpld3/mpld3/mplexporter/exporter.py", line 49, in run
    self.crawl_fig(fig)
  File "/home/prateek/git/mpld3/mpld3/mplexporter/exporter.py", line 116, in crawl_fig
    self.crawl_ax(ax)
  File "/home/prateek/git/mpld3/mpld3/mplexporter/exporter.py", line 130, in crawl_ax
    text_type=ttp)
  File "/home/prateek/git/mpld3/mpld3/mplexporter/exporter.py", line 203, in draw_text
    force_trans=force_trans)
  File "/home/prateek/git/mpld3/mpld3/mplexporter/exporter.py", line 87, in process_transform
    data = (transform - force_trans).transform(data)
TypeError: unsupported operand type(s) for -: 'CompositeAffine2D' and 'BboxTransformTo'
```

Anybody got anything on this?

**Comment by isokrates** [comment]
Hi,

I'm having a similar error (below) when I try to use fig_to_html() on my VM (Ubuntu 12.04.5 LTS). Oddly, this doesn't happen when I run it on my Mac (OS X 10.10.5). The only difference between the VM version and the Mac version is that the VM version has `matplotlib.use('Agg')`, as there's no display, and this is how I have previously got around it. Matplotlib is up to date (1.4.3).

Any idea why I am getting this error?

Cheers!

Chris

`
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/christopher/dd/dd.py", line 501, in gsn_create
    return gsn.gsn('gsn/csv/%s.csv' % output_filename)
  File "/home/christopher/dd/gsn.py", line 254, in gsn
    return makemap('', coordslist, output_filename, quality=quality)
  File "/home/christopher/dd/gsn.py", line 190, in makemap
    fig_html = mpld3.fig_to_html(fig, template_type='general')
  File "/usr/local/lib/python2.7/dist-packages/mpld3/_display.py", line 225, in fig_to_html
    Exporter(renderer, close_mpl=False, **kwargs).run(fig)
  File "/usr/local/lib/python2.7/dist-packages/mpld3/mplexporter/exporter.py", line 49, in run
    self.crawl_fig(fig)
  File "/usr/local/lib/python2.7/dist-packages/mpld3/mplexporter/exporter.py", line 116, in crawl_fig
    self.crawl_ax(ax)
  File "/usr/local/lib/python2.7/dist-packages/mpld3/mplexporter/exporter.py", line 123, in crawl_ax
    self.draw_line(ax, line)
  File "/usr/local/lib/python2.7/dist-packages/mpld3/mplexporter/exporter.py", line 179, in draw_line
    force_trans=force_trans)
  File "/usr/local/lib/python2.7/dist-packages/mpld3/mplexporter/exporter.py", line 96, in process_transform
    if transform.contains_branch(trans):
AttributeError: 'CompositeGenericTransform' object has no attribute 'contains_branch'
`

**Comment by jakevdp** [comment]
mpld3 only currently works with Matplotlib version 1.3. If you use 1.4, you'll get errors. This is due to the fact that the entire mpld3 library is basically a hack, and uses private methods in matplotlib that change unannounced from release to release. If and when matplotlib's serialization framework lands in a release, we'll be able to do this in a more stable manner. But for now it's a known bug that is unlikely to be fixed (unless someone is motivated to dig in and do it). Sorry.

**Comment by isokrates** [comment]
That's fantastic to know - thanks so much. Seems to work fine on my VM now
(with Basemap, too) - thanks again! :)
